version: "3.9"
services:
  app:
    image: localhost/kanaco:dev
    container_name: KanaCo
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true
    networks:
      - kanaco
    volumes:
      - ..:/usr/local/kanaco/src
    environment:
      - TZ=Asia/Tokyo
      - EDITOR=vi
networks:
  kanaco:
volumes:
  kanaco:
